/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, RequestFnResponse, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationUseMutationOptions, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { Mutation, MutationCache, MutationState, UseMutationResult } from "@tanstack/react-query";
export interface AuthService {
    login: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<LoginBody, LoginParameters, TMeta, TSignal>, client?: (schema: LoginSchema, options: ServiceOperationMutationFnOptions<LoginBody, LoginParameters, TMeta, TSignal>) => Promise<RequestFnResponse<LoginData, LoginError>>): Promise<RequestFnResponse<LoginData, LoginError>>;
        /**/
        getMutationKey(parameters: DeepReadonly<LoginParameters> | void): ServiceOperationMutationKey<LoginSchema, LoginParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.auth.login.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.auth.login.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends LoginBody, TContext = unknown>(parameters: DeepReadonly<LoginParameters>, options?: ServiceOperationUseMutationOptions<LoginSchema, LoginData, LoginParameters, TVariables, OperationError<LoginError>, TContext>): UseMutationResult<LoginData, OperationError<LoginError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.auth.login.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.auth.login.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<LoginBody, LoginParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<LoginSchema, LoginData, LoginParameters, TVariables, OperationError<LoginError>, TContext>): UseMutationResult<LoginData, OperationError<LoginError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const loginTotal = qraft.auth.login.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const loginTotal = qraft.auth.login.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext> | MutationFiltersByMutationKey<LoginSchema, LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const loginPendingMutationVariables = qraft.auth.login.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const loginMutationData = qraft.auth.login.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<LoginData, OperationError<LoginError>, MutationVariables<LoginBody, LoginParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext> | MutationFiltersByMutationKey<LoginSchema, LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext>;
            select?: (mutation: Mutation<LoginData, OperationError<LoginError>, MutationVariables<LoginBody, LoginParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /**/
        isMutating<TContext>(filters?: MutationFiltersByParameters<LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext> | MutationFiltersByMutationKey<LoginSchema, LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.auth.login.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.auth.login.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext> | MutationFiltersByMutationKey<LoginSchema, LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext>): Mutation<LoginData, LoginError, MutationVariables<LoginBody, LoginParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext> | MutationFiltersByMutationKey<LoginSchema, LoginBody, LoginData, LoginParameters, OperationError<LoginError>, TContext>): Array<Mutation<LoginData, LoginError, MutationVariables<LoginBody, LoginParameters>, TContext>>;
        };
        schema: LoginSchema;
        types: {
            parameters: LoginParameters;
            data: LoginData;
            error: LoginError;
            body: LoginBody;
        };
    };
}
export const login = {
    schema: {
        method: "post",
        url: "/auth/login",
        mediaType: ["application/json"]
    }
} as {
    schema: LoginSchema;
    [QraftServiceOperationsToken]: AuthService["login"];
};
export const authService = {
    login
} as const;
type LoginSchema = {
    method: "post";
    url: "/auth/login";
    mediaType: [
        "application/json"
    ];
};
type LoginParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type LoginData = paths["/auth/login"]["post"]["responses"]["200"]["content"]["*/*"];
type LoginError = unknown;
type LoginBody = paths["/auth/login"]["post"]["requestBody"]["content"]["application/json"];
