/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationCache, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface EventRequestsService {
    /** @description Rejeita uma solicitação sem alterar o evento. */
    rejectEventRequest: {
        /** @description Rejeita uma solicitação sem alterar o evento. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<RejectEventRequestBody, RejectEventRequestParameters, TMeta, TSignal>, client?: (schema: RejectEventRequestSchema, options: ServiceOperationMutationFnOptions<RejectEventRequestBody, RejectEventRequestParameters, TMeta, TSignal>) => Promise<RequestFnResponse<RejectEventRequestData, RejectEventRequestError>>): Promise<RequestFnResponse<RejectEventRequestData, RejectEventRequestError>>;
        /** @description Rejeita uma solicitação sem alterar o evento. */
        getMutationKey(parameters: DeepReadonly<RejectEventRequestParameters> | void): ServiceOperationMutationKey<RejectEventRequestSchema, RejectEventRequestParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Rejeita uma solicitação sem alterar o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.rejectEventRequest.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.rejectEventRequest.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends RejectEventRequestBody, TContext = unknown>(parameters: DeepReadonly<RejectEventRequestParameters>, options?: ServiceOperationUseMutationOptions<RejectEventRequestSchema, RejectEventRequestData, RejectEventRequestParameters, TVariables, OperationError<RejectEventRequestError>, TContext>): UseMutationResult<RejectEventRequestData, OperationError<RejectEventRequestError>, TVariables | void, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Rejeita uma solicitação sem alterar o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.rejectEventRequest.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.rejectEventRequest.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<RejectEventRequestBody, RejectEventRequestParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<RejectEventRequestSchema, RejectEventRequestData, RejectEventRequestParameters, TVariables, OperationError<RejectEventRequestError>, TContext>): UseMutationResult<RejectEventRequestData, OperationError<RejectEventRequestError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Rejeita uma solicitação sem alterar o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const rejectEventRequestTotal = qraft.eventRequests.rejectEventRequest.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const rejectEventRequestTotal = qraft.eventRequests.rejectEventRequest.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext> | MutationFiltersByMutationKey<RejectEventRequestSchema, RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Rejeita uma solicitação sem alterar o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const rejectEventRequestPendingMutationVariables = qraft.eventRequests.rejectEventRequest.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const rejectEventRequestMutationData = qraft.eventRequests.rejectEventRequest.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<RejectEventRequestData, OperationError<RejectEventRequestError>, MutationVariables<RejectEventRequestBody, RejectEventRequestParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext> | MutationFiltersByMutationKey<RejectEventRequestSchema, RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext>;
            select?: (mutation: Mutation<RejectEventRequestData, OperationError<RejectEventRequestError>, MutationVariables<RejectEventRequestBody, RejectEventRequestParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Rejeita uma solicitação sem alterar o evento. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext> | MutationFiltersByMutationKey<RejectEventRequestSchema, RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Rejeita uma solicitação sem alterar o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.eventRequests.rejectEventRequest.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.eventRequests.rejectEventRequest.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext> | MutationFiltersByMutationKey<RejectEventRequestSchema, RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext>): Mutation<RejectEventRequestData, RejectEventRequestError, MutationVariables<RejectEventRequestBody, RejectEventRequestParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext> | MutationFiltersByMutationKey<RejectEventRequestSchema, RejectEventRequestBody, RejectEventRequestData, RejectEventRequestParameters, OperationError<RejectEventRequestError>, TContext>): Array<Mutation<RejectEventRequestData, RejectEventRequestError, MutationVariables<RejectEventRequestBody, RejectEventRequestParameters>, TContext>>;
        };
        schema: RejectEventRequestSchema;
        types: {
            parameters: RejectEventRequestParameters;
            data: RejectEventRequestData;
            error: RejectEventRequestError;
            body: RejectEventRequestBody;
        };
    };
    /** @description Aprova uma solicitação, efetivando a operação sobre o evento. */
    approveEventRequest: {
        /** @description Aprova uma solicitação, efetivando a operação sobre o evento. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<ApproveEventRequestBody, ApproveEventRequestParameters, TMeta, TSignal>, client?: (schema: ApproveEventRequestSchema, options: ServiceOperationMutationFnOptions<ApproveEventRequestBody, ApproveEventRequestParameters, TMeta, TSignal>) => Promise<RequestFnResponse<ApproveEventRequestData, ApproveEventRequestError>>): Promise<RequestFnResponse<ApproveEventRequestData, ApproveEventRequestError>>;
        /** @description Aprova uma solicitação, efetivando a operação sobre o evento. */
        getMutationKey(parameters: DeepReadonly<ApproveEventRequestParameters> | void): ServiceOperationMutationKey<ApproveEventRequestSchema, ApproveEventRequestParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Aprova uma solicitação, efetivando a operação sobre o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.approveEventRequest.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.approveEventRequest.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends ApproveEventRequestBody, TContext = unknown>(parameters: DeepReadonly<ApproveEventRequestParameters>, options?: ServiceOperationUseMutationOptions<ApproveEventRequestSchema, ApproveEventRequestData, ApproveEventRequestParameters, TVariables, OperationError<ApproveEventRequestError>, TContext>): UseMutationResult<ApproveEventRequestData, OperationError<ApproveEventRequestError>, TVariables | void, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Aprova uma solicitação, efetivando a operação sobre o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.approveEventRequest.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.approveEventRequest.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<ApproveEventRequestBody, ApproveEventRequestParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<ApproveEventRequestSchema, ApproveEventRequestData, ApproveEventRequestParameters, TVariables, OperationError<ApproveEventRequestError>, TContext>): UseMutationResult<ApproveEventRequestData, OperationError<ApproveEventRequestError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Aprova uma solicitação, efetivando a operação sobre o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const approveEventRequestTotal = qraft.eventRequests.approveEventRequest.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const approveEventRequestTotal = qraft.eventRequests.approveEventRequest.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext> | MutationFiltersByMutationKey<ApproveEventRequestSchema, ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Aprova uma solicitação, efetivando a operação sobre o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const approveEventRequestPendingMutationVariables = qraft.eventRequests.approveEventRequest.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const approveEventRequestMutationData = qraft.eventRequests.approveEventRequest.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<ApproveEventRequestData, OperationError<ApproveEventRequestError>, MutationVariables<ApproveEventRequestBody, ApproveEventRequestParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext> | MutationFiltersByMutationKey<ApproveEventRequestSchema, ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext>;
            select?: (mutation: Mutation<ApproveEventRequestData, OperationError<ApproveEventRequestError>, MutationVariables<ApproveEventRequestBody, ApproveEventRequestParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Aprova uma solicitação, efetivando a operação sobre o evento. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext> | MutationFiltersByMutationKey<ApproveEventRequestSchema, ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Aprova uma solicitação, efetivando a operação sobre o evento.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.eventRequests.approveEventRequest.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.eventRequests.approveEventRequest.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext> | MutationFiltersByMutationKey<ApproveEventRequestSchema, ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext>): Mutation<ApproveEventRequestData, ApproveEventRequestError, MutationVariables<ApproveEventRequestBody, ApproveEventRequestParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext> | MutationFiltersByMutationKey<ApproveEventRequestSchema, ApproveEventRequestBody, ApproveEventRequestData, ApproveEventRequestParameters, OperationError<ApproveEventRequestError>, TContext>): Array<Mutation<ApproveEventRequestData, ApproveEventRequestError, MutationVariables<ApproveEventRequestBody, ApproveEventRequestParameters>, TContext>>;
        };
        schema: ApproveEventRequestSchema;
        types: {
            parameters: ApproveEventRequestParameters;
            data: ApproveEventRequestData;
            error: ApproveEventRequestError;
            body: ApproveEventRequestBody;
        };
    };
    /** @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
    requestEventUpdate: {
        /** @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<RequestEventUpdateBody, RequestEventUpdateParameters, TMeta, TSignal>, client?: (schema: RequestEventUpdateSchema, options: ServiceOperationMutationFnOptions<RequestEventUpdateBody, RequestEventUpdateParameters, TMeta, TSignal>) => Promise<RequestFnResponse<RequestEventUpdateData, RequestEventUpdateError>>): Promise<RequestFnResponse<RequestEventUpdateData, RequestEventUpdateError>>;
        /** @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        getMutationKey(parameters: DeepReadonly<RequestEventUpdateParameters> | void): ServiceOperationMutationKey<RequestEventUpdateSchema, RequestEventUpdateParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventUpdate.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventUpdate.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends RequestEventUpdateBody, TContext = unknown>(parameters: DeepReadonly<RequestEventUpdateParameters>, options?: ServiceOperationUseMutationOptions<RequestEventUpdateSchema, RequestEventUpdateData, RequestEventUpdateParameters, TVariables, OperationError<RequestEventUpdateError>, TContext>): UseMutationResult<RequestEventUpdateData, OperationError<RequestEventUpdateError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventUpdate.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventUpdate.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<RequestEventUpdateBody, RequestEventUpdateParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<RequestEventUpdateSchema, RequestEventUpdateData, RequestEventUpdateParameters, TVariables, OperationError<RequestEventUpdateError>, TContext>): UseMutationResult<RequestEventUpdateData, OperationError<RequestEventUpdateError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const requestEventUpdateTotal = qraft.eventRequests.requestEventUpdate.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const requestEventUpdateTotal = qraft.eventRequests.requestEventUpdate.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext> | MutationFiltersByMutationKey<RequestEventUpdateSchema, RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const requestEventUpdatePendingMutationVariables = qraft.eventRequests.requestEventUpdate.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const requestEventUpdateMutationData = qraft.eventRequests.requestEventUpdate.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<RequestEventUpdateData, OperationError<RequestEventUpdateError>, MutationVariables<RequestEventUpdateBody, RequestEventUpdateParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext> | MutationFiltersByMutationKey<RequestEventUpdateSchema, RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext>;
            select?: (mutation: Mutation<RequestEventUpdateData, OperationError<RequestEventUpdateError>, MutationVariables<RequestEventUpdateBody, RequestEventUpdateParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext> | MutationFiltersByMutationKey<RequestEventUpdateSchema, RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventUpdate.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventUpdate.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext> | MutationFiltersByMutationKey<RequestEventUpdateSchema, RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext>): Mutation<RequestEventUpdateData, RequestEventUpdateError, MutationVariables<RequestEventUpdateBody, RequestEventUpdateParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext> | MutationFiltersByMutationKey<RequestEventUpdateSchema, RequestEventUpdateBody, RequestEventUpdateData, RequestEventUpdateParameters, OperationError<RequestEventUpdateError>, TContext>): Array<Mutation<RequestEventUpdateData, RequestEventUpdateError, MutationVariables<RequestEventUpdateBody, RequestEventUpdateParameters>, TContext>>;
        };
        schema: RequestEventUpdateSchema;
        types: {
            parameters: RequestEventUpdateParameters;
            data: RequestEventUpdateData;
            error: RequestEventUpdateError;
            body: RequestEventUpdateBody;
        };
    };
    /** @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada. */
    requestEventCreation: {
        /** @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<RequestEventCreationBody, RequestEventCreationParameters, TMeta, TSignal>, client?: (schema: RequestEventCreationSchema, options: ServiceOperationMutationFnOptions<RequestEventCreationBody, RequestEventCreationParameters, TMeta, TSignal>) => Promise<RequestFnResponse<RequestEventCreationData, RequestEventCreationError>>): Promise<RequestFnResponse<RequestEventCreationData, RequestEventCreationError>>;
        /** @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada. */
        getMutationKey(parameters: DeepReadonly<RequestEventCreationParameters> | void): ServiceOperationMutationKey<RequestEventCreationSchema, RequestEventCreationParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCreation.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCreation.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends RequestEventCreationBody, TContext = unknown>(parameters: DeepReadonly<RequestEventCreationParameters>, options?: ServiceOperationUseMutationOptions<RequestEventCreationSchema, RequestEventCreationData, RequestEventCreationParameters, TVariables, OperationError<RequestEventCreationError>, TContext>): UseMutationResult<RequestEventCreationData, OperationError<RequestEventCreationError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCreation.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCreation.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<RequestEventCreationBody, RequestEventCreationParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<RequestEventCreationSchema, RequestEventCreationData, RequestEventCreationParameters, TVariables, OperationError<RequestEventCreationError>, TContext>): UseMutationResult<RequestEventCreationData, OperationError<RequestEventCreationError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const requestEventCreationTotal = qraft.eventRequests.requestEventCreation.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const requestEventCreationTotal = qraft.eventRequests.requestEventCreation.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext> | MutationFiltersByMutationKey<RequestEventCreationSchema, RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const requestEventCreationPendingMutationVariables = qraft.eventRequests.requestEventCreation.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const requestEventCreationMutationData = qraft.eventRequests.requestEventCreation.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<RequestEventCreationData, OperationError<RequestEventCreationError>, MutationVariables<RequestEventCreationBody, RequestEventCreationParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext> | MutationFiltersByMutationKey<RequestEventCreationSchema, RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext>;
            select?: (mutation: Mutation<RequestEventCreationData, OperationError<RequestEventCreationError>, MutationVariables<RequestEventCreationBody, RequestEventCreationParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext> | MutationFiltersByMutationKey<RequestEventCreationSchema, RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventCreation.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventCreation.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext> | MutationFiltersByMutationKey<RequestEventCreationSchema, RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext>): Mutation<RequestEventCreationData, RequestEventCreationError, MutationVariables<RequestEventCreationBody, RequestEventCreationParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext> | MutationFiltersByMutationKey<RequestEventCreationSchema, RequestEventCreationBody, RequestEventCreationData, RequestEventCreationParameters, OperationError<RequestEventCreationError>, TContext>): Array<Mutation<RequestEventCreationData, RequestEventCreationError, MutationVariables<RequestEventCreationBody, RequestEventCreationParameters>, TContext>>;
        };
        schema: RequestEventCreationSchema;
        types: {
            parameters: RequestEventCreationParameters;
            data: RequestEventCreationData;
            error: RequestEventCreationError;
            body: RequestEventCreationBody;
        };
    };
    /** @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
    requestEventCancellation: {
        /** @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<RequestEventCancellationBody, RequestEventCancellationParameters, TMeta, TSignal>, client?: (schema: RequestEventCancellationSchema, options: ServiceOperationMutationFnOptions<RequestEventCancellationBody, RequestEventCancellationParameters, TMeta, TSignal>) => Promise<RequestFnResponse<RequestEventCancellationData, RequestEventCancellationError>>): Promise<RequestFnResponse<RequestEventCancellationData, RequestEventCancellationError>>;
        /** @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        getMutationKey(parameters: DeepReadonly<RequestEventCancellationParameters> | void): ServiceOperationMutationKey<RequestEventCancellationSchema, RequestEventCancellationParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCancellation.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCancellation.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends RequestEventCancellationBody, TContext = unknown>(parameters: DeepReadonly<RequestEventCancellationParameters>, options?: ServiceOperationUseMutationOptions<RequestEventCancellationSchema, RequestEventCancellationData, RequestEventCancellationParameters, TVariables, OperationError<RequestEventCancellationError>, TContext>): UseMutationResult<RequestEventCancellationData, OperationError<RequestEventCancellationError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCancellation.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.eventRequests.requestEventCancellation.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<RequestEventCancellationBody, RequestEventCancellationParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<RequestEventCancellationSchema, RequestEventCancellationData, RequestEventCancellationParameters, TVariables, OperationError<RequestEventCancellationError>, TContext>): UseMutationResult<RequestEventCancellationData, OperationError<RequestEventCancellationError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const requestEventCancellationTotal = qraft.eventRequests.requestEventCancellation.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const requestEventCancellationTotal = qraft.eventRequests.requestEventCancellation.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext> | MutationFiltersByMutationKey<RequestEventCancellationSchema, RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const requestEventCancellationPendingMutationVariables = qraft.eventRequests.requestEventCancellation.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const requestEventCancellationMutationData = qraft.eventRequests.requestEventCancellation.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<RequestEventCancellationData, OperationError<RequestEventCancellationError>, MutationVariables<RequestEventCancellationBody, RequestEventCancellationParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext> | MutationFiltersByMutationKey<RequestEventCancellationSchema, RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext>;
            select?: (mutation: Mutation<RequestEventCancellationData, OperationError<RequestEventCancellationError>, MutationVariables<RequestEventCancellationBody, RequestEventCancellationParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext> | MutationFiltersByMutationKey<RequestEventCancellationSchema, RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventCancellation.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.eventRequests.requestEventCancellation.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext> | MutationFiltersByMutationKey<RequestEventCancellationSchema, RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext>): Mutation<RequestEventCancellationData, RequestEventCancellationError, MutationVariables<RequestEventCancellationBody, RequestEventCancellationParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext> | MutationFiltersByMutationKey<RequestEventCancellationSchema, RequestEventCancellationBody, RequestEventCancellationData, RequestEventCancellationParameters, OperationError<RequestEventCancellationError>, TContext>): Array<Mutation<RequestEventCancellationData, RequestEventCancellationError, MutationVariables<RequestEventCancellationBody, RequestEventCancellationParameters>, TContext>>;
        };
        schema: RequestEventCancellationSchema;
        types: {
            parameters: RequestEventCancellationParameters;
            data: RequestEventCancellationData;
            error: RequestEventCancellationError;
            body: RequestEventCancellationBody;
        };
    };
    /** @description Retorna todas as solicitações de eventos. */
    listEventRequests: {
        /** @description Retorna todas as solicitações de eventos. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<ListEventRequestsSchema, ListEventRequestsParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<ListEventRequestsParameters, TMeta, TSignal> | void), client?: (schema: ListEventRequestsSchema, options: {
            parameters: ListEventRequestsParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<ListEventRequestsData, ListEventRequestsError>>): Promise<RequestFnResponse<ListEventRequestsData, ListEventRequestsError>>;
        /** @description Retorna todas as solicitações de eventos. */
        getQueryKey(parameters: DeepReadonly<ListEventRequestsParameters> | void): ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.eventRequests.listEventRequests.useQuery()
         * ```
         */
        useQuery<TData = ListEventRequestsData>(parameters: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options?: Omit<UndefinedInitialDataOptions<ListEventRequestsData, ListEventRequestsError, TData, ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>>, "queryKey">): UseQueryResult<TData, OperationError<ListEventRequestsError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.eventRequests.listEventRequests.useQuery()
         * ```
         */
        useQuery<TData = ListEventRequestsData>(parameters: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options: Omit<DefinedInitialDataOptions<ListEventRequestsData, ListEventRequestsError, TData, ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<ListEventRequestsError>>;
        /** @description Retorna todas as solicitações de eventos. */
        getInfiniteQueryKey(parameters: DeepReadonly<ListEventRequestsParameters> | void): ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.eventRequests.listEventRequests.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ListEventRequestsParameters, TQueryFnData = ListEventRequestsData, TData = OperationInfiniteData<TQueryFnData, ListEventRequestsParameters>>(parameters: ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, ListEventRequestsError, TData, ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<ListEventRequestsError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.eventRequests.listEventRequests.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ListEventRequestsParameters, TQueryFnData = ListEventRequestsData, TData = OperationInfiniteData<TQueryFnData, ListEventRequestsParameters>>(parameters: ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, ListEventRequestsError, TData, ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ListEventRequestsData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<ListEventRequestsError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const listEventRequestsTotal = qraft.eventRequests.listEventRequests.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const listEventRequestsResults = qraft.eventRequests.listEventRequests.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listEventRequestsResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const listEventRequestsCombinedResults = qraft.eventRequests.listEventRequests.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listEventRequestsCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<ListEventRequestsSchema, ListEventRequestsParameters, ListEventRequestsData, ListEventRequestsError>>, TCombinedResult = Array<UseQueryResult<ListEventRequestsData, ListEventRequestsError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<ListEventRequestsData, ListEventRequestsError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.eventRequests.listEventRequests.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = ListEventRequestsData>(parameters: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options?: Omit<UseSuspenseQueryOptions<ListEventRequestsData, ListEventRequestsError, TData, ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<ListEventRequestsError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.eventRequests.listEventRequests.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends ListEventRequestsParameters, TData = ListEventRequestsData>(parameters: ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<ListEventRequestsData, ListEventRequestsError, OperationInfiniteData<TData, ListEventRequestsParameters>, ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ListEventRequestsData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, ListEventRequestsParameters>, OperationError<ListEventRequestsError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @description Retorna todas as solicitações de eventos.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const listEventRequestsData = qraft.eventRequests.listEventRequests.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listEventRequestsResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const listEventRequestsCombinedData = qraft.eventRequests.listEventRequests.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listEventRequestsCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<ListEventRequestsSchema, ListEventRequestsParameters, ListEventRequestsData, ListEventRequestsError>>, TCombinedResult = Array<UseSuspenseQueryResult<ListEventRequestsData, ListEventRequestsError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<ListEventRequestsData, ListEventRequestsError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @description Retorna todas as solicitações de eventos. */
        fetchQuery(options: ServiceOperationFetchQueryOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, ListEventRequestsError> | void): Promise<ListEventRequestsData>;
        /** @description Retorna todas as solicitações de eventos. */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, ListEventRequestsError> | void): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, ListEventRequestsError> | void): Promise<ListEventRequestsData>;
        /** @description Retorna todas as solicitações de eventos. */
        fetchInfiniteQuery<TPageParam extends ListEventRequestsParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, DeepReadonly<TPageParam>, ListEventRequestsError> | void): Promise<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>>;
        /** @description Retorna todas as solicitações de eventos. */
        prefetchInfiniteQuery<TPageParam extends ListEventRequestsParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, DeepReadonly<TPageParam>, ListEventRequestsError> | void): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        ensureInfiniteQueryData<TPageParam extends ListEventRequestsParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<ListEventRequestsSchema, ListEventRequestsData, ListEventRequestsParameters, DeepReadonly<TPageParam>, ListEventRequestsError> | void): Promise<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>>;
        /** @description Retorna todas as solicitações de eventos. */
        getQueryData(parameters: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void)): ListEventRequestsData | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void)): OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters> | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>,
            data: NoInfer<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>,
            data: ListEventRequestsData | undefined
        ]>;
        /** @description Retorna todas as solicitações de eventos. */
        getQueryState(parameters: ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | (DeepReadonly<ListEventRequestsParameters> | void)): QueryState<ListEventRequestsData, ListEventRequestsError> | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        getInfiniteQueryState(parameters: DeepReadonly<ListEventRequestsParameters> | ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters> | void): QueryState<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>, ListEventRequestsError> | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        setQueryData(parameters: (DeepReadonly<ListEventRequestsParameters> | undefined) | ServiceOperationQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>, updater: Updater<NoInfer<ListEventRequestsData> | undefined, NoInfer<DeepReadonly<ListEventRequestsData>> | undefined>, options?: SetDataOptions): ListEventRequestsData | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        setInfiniteQueryData(parameters: (DeepReadonly<ListEventRequestsParameters> | undefined) | ServiceOperationInfiniteQueryKey<ListEventRequestsSchema, ListEventRequestsParameters>, updater: Updater<NoInfer<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<ListEventRequestsData, ListEventRequestsParameters> | undefined;
        /** @description Retorna todas as solicitações de eventos. */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>, updater: Updater<NoInfer<ListEventRequestsData> | undefined, NoInfer<ListEventRequestsData> | undefined>, options?: SetDataOptions): Array<ListEventRequestsData | undefined>;
        /** @description Retorna todas as solicitações de eventos. */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>, options?: InvalidateOptions): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>, options?: RefetchOptions): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>, options?: CancelOptions): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>): void;
        /** @description Retorna todas as solicitações de eventos. */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>, options?: ResetOptions): Promise<void>;
        /** @description Retorna todas as solicitações de eventos. */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError> | QueryFiltersByQueryKey<ListEventRequestsSchema, ListEventRequestsData, TInfinite, ListEventRequestsParameters, ListEventRequestsError>): number;
        schema: ListEventRequestsSchema;
        types: {
            parameters: ListEventRequestsParameters;
            data: ListEventRequestsData;
            error: ListEventRequestsError;
        };
    };
}
/** @description Rejeita uma solicitação sem alterar o evento. */
export const rejectEventRequest = {
    schema: {
        method: "post",
        url: "/event-requests/{id}/reject"
    }
} as {
    schema: RejectEventRequestSchema;
    [QraftServiceOperationsToken]: EventRequestsService["rejectEventRequest"];
};
/** @description Aprova uma solicitação, efetivando a operação sobre o evento. */
export const approveEventRequest = {
    schema: {
        method: "post",
        url: "/event-requests/{id}/approve"
    }
} as {
    schema: ApproveEventRequestSchema;
    [QraftServiceOperationsToken]: EventRequestsService["approveEventRequest"];
};
/** @description Solicita a atualização de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
export const requestEventUpdate = {
    schema: {
        method: "post",
        url: "/event-requests/update-event",
        mediaType: ["application/json"]
    }
} as {
    schema: RequestEventUpdateSchema;
    [QraftServiceOperationsToken]: EventRequestsService["requestEventUpdate"];
};
/** @description Solicita a criação de um novo evento. Fica pendente até ser aprovada ou rejeitada. */
export const requestEventCreation = {
    schema: {
        method: "post",
        url: "/event-requests/create-event",
        mediaType: ["application/json"]
    }
} as {
    schema: RequestEventCreationSchema;
    [QraftServiceOperationsToken]: EventRequestsService["requestEventCreation"];
};
/** @description Solicita o cancelamento de um evento existente. Fica pendente até ser aprovada ou rejeitada. */
export const requestEventCancellation = {
    schema: {
        method: "post",
        url: "/event-requests/cancel-event",
        mediaType: ["application/json"]
    }
} as {
    schema: RequestEventCancellationSchema;
    [QraftServiceOperationsToken]: EventRequestsService["requestEventCancellation"];
};
/** @description Retorna todas as solicitações de eventos. */
export const listEventRequests = {
    schema: {
        method: "get",
        url: "/event-requests"
    }
} as {
    schema: ListEventRequestsSchema;
    [QraftServiceOperationsToken]: EventRequestsService["listEventRequests"];
};
export const eventRequestsService = {
    rejectEventRequest,
    approveEventRequest,
    requestEventUpdate,
    requestEventCreation,
    requestEventCancellation,
    listEventRequests
} as const;
type RejectEventRequestSchema = {
    method: "post";
    url: "/event-requests/{id}/reject";
};
type RejectEventRequestParameters = paths["/event-requests/{id}/reject"]["post"]["parameters"];
type RejectEventRequestData = null;
type RejectEventRequestError = paths["/event-requests/{id}/reject"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests/{id}/reject"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests/{id}/reject"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests/{id}/reject"]["post"]["responses"]["422"]["content"]["*/*"];
type RejectEventRequestBody = undefined;
type ApproveEventRequestSchema = {
    method: "post";
    url: "/event-requests/{id}/approve";
};
type ApproveEventRequestParameters = paths["/event-requests/{id}/approve"]["post"]["parameters"];
type ApproveEventRequestData = null;
type ApproveEventRequestError = paths["/event-requests/{id}/approve"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests/{id}/approve"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests/{id}/approve"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests/{id}/approve"]["post"]["responses"]["422"]["content"]["*/*"];
type ApproveEventRequestBody = undefined;
type RequestEventUpdateSchema = {
    method: "post";
    url: "/event-requests/update-event";
    mediaType: [
        "application/json"
    ];
};
type RequestEventUpdateParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type RequestEventUpdateData = paths["/event-requests/update-event"]["post"]["responses"]["201"]["content"]["*/*"];
type RequestEventUpdateError = paths["/event-requests/update-event"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests/update-event"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests/update-event"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests/update-event"]["post"]["responses"]["422"]["content"]["*/*"];
type RequestEventUpdateBody = paths["/event-requests/update-event"]["post"]["requestBody"]["content"]["application/json"];
type RequestEventCreationSchema = {
    method: "post";
    url: "/event-requests/create-event";
    mediaType: [
        "application/json"
    ];
};
type RequestEventCreationParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type RequestEventCreationData = paths["/event-requests/create-event"]["post"]["responses"]["201"]["content"]["*/*"];
type RequestEventCreationError = paths["/event-requests/create-event"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests/create-event"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests/create-event"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests/create-event"]["post"]["responses"]["422"]["content"]["*/*"];
type RequestEventCreationBody = paths["/event-requests/create-event"]["post"]["requestBody"]["content"]["application/json"];
type RequestEventCancellationSchema = {
    method: "post";
    url: "/event-requests/cancel-event";
    mediaType: [
        "application/json"
    ];
};
type RequestEventCancellationParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type RequestEventCancellationData = paths["/event-requests/cancel-event"]["post"]["responses"]["201"]["content"]["*/*"];
type RequestEventCancellationError = paths["/event-requests/cancel-event"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests/cancel-event"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests/cancel-event"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests/cancel-event"]["post"]["responses"]["422"]["content"]["*/*"];
type RequestEventCancellationBody = paths["/event-requests/cancel-event"]["post"]["requestBody"]["content"]["application/json"];
type ListEventRequestsSchema = {
    method: "get";
    url: "/event-requests";
};
type ListEventRequestsParameters = undefined;
type ListEventRequestsData = paths["/event-requests"]["get"]["responses"]["200"]["content"]["*/*"];
type ListEventRequestsError = paths["/event-requests"]["get"]["responses"]["400"]["content"]["*/*"] | paths["/event-requests"]["get"]["responses"]["404"]["content"]["*/*"] | paths["/event-requests"]["get"]["responses"]["409"]["content"]["*/*"] | paths["/event-requests"]["get"]["responses"]["422"]["content"]["*/*"];
