/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { UsersService } from "./UsersService";
import { usersService } from "./UsersService";
import type { AuthService } from "./AuthService";
import { authService } from "./AuthService";
export type Services = {
    users: UsersService;
    auth: AuthService;
};
export const services: {
    users: typeof usersService;
    auth: typeof authService;
} = {
    users: usersService,
    auth: authService
};
