/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationCache, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface RoomTypesService {
    /** @description Retorna os dados de um tipo de sala pelo seu ID. */
    findById2: {
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<FindById2Schema, FindById2Parameters, TMeta, TSignal> | (QueryFnOptionsByParameters<FindById2Parameters, TMeta, TSignal>), client?: (schema: FindById2Schema, options: {
            parameters: FindById2Parameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<FindById2Data, FindById2Error>>): Promise<RequestFnResponse<FindById2Data, FindById2Error>>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getQueryKey(parameters: DeepReadonly<FindById2Parameters>): ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.roomTypes.findById2.useQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useQuery<TData = FindById2Data>(parameters: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options?: Omit<UndefinedInitialDataOptions<FindById2Data, FindById2Error, TData, ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>>, "queryKey">): UseQueryResult<TData, OperationError<FindById2Error>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.roomTypes.findById2.useQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useQuery<TData = FindById2Data>(parameters: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options: Omit<DefinedInitialDataOptions<FindById2Data, FindById2Error, TData, ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<FindById2Error>>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getInfiniteQueryKey(parameters: DeepReadonly<FindById2Parameters>): ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findById2.useInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindById2Parameters, TQueryFnData = FindById2Data, TData = OperationInfiniteData<TQueryFnData, FindById2Parameters>>(parameters: ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, FindById2Error, TData, ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<FindById2Error>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findById2.useInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindById2Parameters, TQueryFnData = FindById2Data, TData = OperationInfiniteData<TQueryFnData, FindById2Parameters>>(parameters: ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, FindById2Error, TData, ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindById2Data, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<FindById2Error>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const findById2Total = qraft.roomTypes.findById2.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const findById2ByParametersTotal = qraft.roomTypes.findById2.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const findById2Results = qraft.roomTypes.findById2.useQueries({
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findById2Results.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const findById2CombinedResults = qraft.roomTypes.findById2.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findById2CombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<FindById2Schema, FindById2Parameters, FindById2Data, FindById2Error>>, TCombinedResult = Array<UseQueryResult<FindById2Data, FindById2Error>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<FindById2Data, FindById2Error>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.roomTypes.findById2.useSuspenseQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = FindById2Data>(parameters: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options?: Omit<UseSuspenseQueryOptions<FindById2Data, FindById2Error, TData, ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<FindById2Error>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findById2.useSuspenseInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends FindById2Parameters, TData = FindById2Data>(parameters: ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>), options: Omit<UseSuspenseInfiniteQueryOptions<FindById2Data, FindById2Error, OperationInfiniteData<TData, FindById2Parameters>, ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindById2Data, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, FindById2Parameters>, OperationError<FindById2Error>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @description Retorna os dados de um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const findById2Data = qraft.roomTypes.findById2.useSuspenseQueries({
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findById2Results.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const findById2CombinedData = qraft.roomTypes.findById2.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findById2CombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<FindById2Schema, FindById2Parameters, FindById2Data, FindById2Error>>, TCombinedResult = Array<UseSuspenseQueryResult<FindById2Data, FindById2Error>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<FindById2Data, FindById2Error>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        fetchQuery(options: ServiceOperationFetchQueryOptions<FindById2Schema, FindById2Data, FindById2Parameters, FindById2Error>): Promise<FindById2Data>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<FindById2Schema, FindById2Data, FindById2Parameters, FindById2Error>): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<FindById2Schema, FindById2Data, FindById2Parameters, FindById2Error>): Promise<FindById2Data>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        fetchInfiniteQuery<TPageParam extends FindById2Parameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindById2Schema, FindById2Data, FindById2Parameters, DeepReadonly<TPageParam>, FindById2Error>): Promise<OperationInfiniteData<FindById2Data, FindById2Parameters>>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        prefetchInfiniteQuery<TPageParam extends FindById2Parameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindById2Schema, FindById2Data, FindById2Parameters, DeepReadonly<TPageParam>, FindById2Error>): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        ensureInfiniteQueryData<TPageParam extends FindById2Parameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<FindById2Schema, FindById2Data, FindById2Parameters, DeepReadonly<TPageParam>, FindById2Error>): Promise<OperationInfiniteData<FindById2Data, FindById2Parameters>>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getQueryData(parameters: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>)): FindById2Data | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>)): OperationInfiniteData<FindById2Data, FindById2Parameters> | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>,
            data: NoInfer<OperationInfiniteData<FindById2Data, FindById2Parameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>,
            data: FindById2Data | undefined
        ]>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getQueryState(parameters: ServiceOperationQueryKey<FindById2Schema, FindById2Parameters> | (DeepReadonly<FindById2Parameters>)): QueryState<FindById2Data, FindById2Error> | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        getInfiniteQueryState(parameters: DeepReadonly<FindById2Parameters> | ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>): QueryState<OperationInfiniteData<FindById2Data, FindById2Parameters>, FindById2Error> | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        setQueryData(parameters: (DeepReadonly<FindById2Parameters>) | ServiceOperationQueryKey<FindById2Schema, FindById2Parameters>, updater: Updater<NoInfer<FindById2Data> | undefined, NoInfer<DeepReadonly<FindById2Data>> | undefined>, options?: SetDataOptions): FindById2Data | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        setInfiniteQueryData(parameters: (DeepReadonly<FindById2Parameters>) | ServiceOperationInfiniteQueryKey<FindById2Schema, FindById2Parameters>, updater: Updater<NoInfer<OperationInfiniteData<FindById2Data, FindById2Parameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<FindById2Data, FindById2Parameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<FindById2Data, FindById2Parameters> | undefined;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>, updater: Updater<NoInfer<FindById2Data> | undefined, NoInfer<FindById2Data> | undefined>, options?: SetDataOptions): Array<FindById2Data | undefined>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>, options?: InvalidateOptions): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>, options?: RefetchOptions): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>, options?: CancelOptions): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>): void;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>, options?: ResetOptions): Promise<void>;
        /** @description Retorna os dados de um tipo de sala pelo seu ID. */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error> | QueryFiltersByQueryKey<FindById2Schema, FindById2Data, TInfinite, FindById2Parameters, FindById2Error>): number;
        schema: FindById2Schema;
        types: {
            parameters: FindById2Parameters;
            data: FindById2Data;
            error: FindById2Error;
        };
    };
    /** @description Atualiza os dados de um tipo de sala. */
    updateById1: {
        /** @description Atualiza os dados de um tipo de sala. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<UpdateById1Body, UpdateById1Parameters, TMeta, TSignal>, client?: (schema: UpdateById1Schema, options: ServiceOperationMutationFnOptions<UpdateById1Body, UpdateById1Parameters, TMeta, TSignal>) => Promise<RequestFnResponse<UpdateById1Data, UpdateById1Error>>): Promise<RequestFnResponse<UpdateById1Data, UpdateById1Error>>;
        /** @description Atualiza os dados de um tipo de sala. */
        getMutationKey(parameters: DeepReadonly<UpdateById1Parameters> | void): ServiceOperationMutationKey<UpdateById1Schema, UpdateById1Parameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Atualiza os dados de um tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateById1.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateById1.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends UpdateById1Body, TContext = unknown>(parameters: DeepReadonly<UpdateById1Parameters>, options?: ServiceOperationUseMutationOptions<UpdateById1Schema, UpdateById1Data, UpdateById1Parameters, TVariables, OperationError<UpdateById1Error>, TContext>): UseMutationResult<UpdateById1Data, OperationError<UpdateById1Error>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Atualiza os dados de um tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateById1.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateById1.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<UpdateById1Body, UpdateById1Parameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<UpdateById1Schema, UpdateById1Data, UpdateById1Parameters, TVariables, OperationError<UpdateById1Error>, TContext>): UseMutationResult<UpdateById1Data, OperationError<UpdateById1Error>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Atualiza os dados de um tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const updateById1Total = qraft.roomTypes.updateById1.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const updateById1Total = qraft.roomTypes.updateById1.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext> | MutationFiltersByMutationKey<UpdateById1Schema, UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Atualiza os dados de um tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const updateById1PendingMutationVariables = qraft.roomTypes.updateById1.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const updateById1MutationData = qraft.roomTypes.updateById1.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<UpdateById1Data, OperationError<UpdateById1Error>, MutationVariables<UpdateById1Body, UpdateById1Parameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext> | MutationFiltersByMutationKey<UpdateById1Schema, UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext>;
            select?: (mutation: Mutation<UpdateById1Data, OperationError<UpdateById1Error>, MutationVariables<UpdateById1Body, UpdateById1Parameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Atualiza os dados de um tipo de sala. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext> | MutationFiltersByMutationKey<UpdateById1Schema, UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Atualiza os dados de um tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.roomTypes.updateById1.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.roomTypes.updateById1.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext> | MutationFiltersByMutationKey<UpdateById1Schema, UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext>): Mutation<UpdateById1Data, UpdateById1Error, MutationVariables<UpdateById1Body, UpdateById1Parameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext> | MutationFiltersByMutationKey<UpdateById1Schema, UpdateById1Body, UpdateById1Data, UpdateById1Parameters, OperationError<UpdateById1Error>, TContext>): Array<Mutation<UpdateById1Data, UpdateById1Error, MutationVariables<UpdateById1Body, UpdateById1Parameters>, TContext>>;
        };
        schema: UpdateById1Schema;
        types: {
            parameters: UpdateById1Parameters;
            data: UpdateById1Data;
            error: UpdateById1Error;
            body: UpdateById1Body;
        };
    };
    /** @description Desativa um tipo de sala pelo seu ID (soft delete). */
    deleteById2: {
        /** @description Desativa um tipo de sala pelo seu ID (soft delete). */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<DeleteById2Body, DeleteById2Parameters, TMeta, TSignal>, client?: (schema: DeleteById2Schema, options: ServiceOperationMutationFnOptions<DeleteById2Body, DeleteById2Parameters, TMeta, TSignal>) => Promise<RequestFnResponse<DeleteById2Data, DeleteById2Error>>): Promise<RequestFnResponse<DeleteById2Data, DeleteById2Error>>;
        /** @description Desativa um tipo de sala pelo seu ID (soft delete). */
        getMutationKey(parameters: DeepReadonly<DeleteById2Parameters> | void): ServiceOperationMutationKey<DeleteById2Schema, DeleteById2Parameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Desativa um tipo de sala pelo seu ID (soft delete).
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.deleteById2.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.deleteById2.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends DeleteById2Body, TContext = unknown>(parameters: DeepReadonly<DeleteById2Parameters>, options?: ServiceOperationUseMutationOptions<DeleteById2Schema, DeleteById2Data, DeleteById2Parameters, TVariables, OperationError<DeleteById2Error>, TContext>): UseMutationResult<DeleteById2Data, OperationError<DeleteById2Error>, TVariables | void, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Desativa um tipo de sala pelo seu ID (soft delete).
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.deleteById2.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.deleteById2.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<DeleteById2Body, DeleteById2Parameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<DeleteById2Schema, DeleteById2Data, DeleteById2Parameters, TVariables, OperationError<DeleteById2Error>, TContext>): UseMutationResult<DeleteById2Data, OperationError<DeleteById2Error>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Desativa um tipo de sala pelo seu ID (soft delete).
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const deleteById2Total = qraft.roomTypes.deleteById2.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const deleteById2Total = qraft.roomTypes.deleteById2.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext> | MutationFiltersByMutationKey<DeleteById2Schema, DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Desativa um tipo de sala pelo seu ID (soft delete).
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const deleteById2PendingMutationVariables = qraft.roomTypes.deleteById2.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const deleteById2MutationData = qraft.roomTypes.deleteById2.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<DeleteById2Data, OperationError<DeleteById2Error>, MutationVariables<DeleteById2Body, DeleteById2Parameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext> | MutationFiltersByMutationKey<DeleteById2Schema, DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext>;
            select?: (mutation: Mutation<DeleteById2Data, OperationError<DeleteById2Error>, MutationVariables<DeleteById2Body, DeleteById2Parameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Desativa um tipo de sala pelo seu ID (soft delete). */
        isMutating<TContext>(filters?: MutationFiltersByParameters<DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext> | MutationFiltersByMutationKey<DeleteById2Schema, DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Desativa um tipo de sala pelo seu ID (soft delete).
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.roomTypes.deleteById2.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.roomTypes.deleteById2.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext> | MutationFiltersByMutationKey<DeleteById2Schema, DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext>): Mutation<DeleteById2Data, DeleteById2Error, MutationVariables<DeleteById2Body, DeleteById2Parameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext> | MutationFiltersByMutationKey<DeleteById2Schema, DeleteById2Body, DeleteById2Data, DeleteById2Parameters, OperationError<DeleteById2Error>, TContext>): Array<Mutation<DeleteById2Data, DeleteById2Error, MutationVariables<DeleteById2Body, DeleteById2Parameters>, TContext>>;
        };
        schema: DeleteById2Schema;
        types: {
            parameters: DeleteById2Parameters;
            data: DeleteById2Data;
            error: DeleteById2Error;
            body: DeleteById2Body;
        };
    };
    /** @description Ativa ou desativa um tipo de sala pelo seu ID. */
    updateStatus1: {
        /** @description Ativa ou desativa um tipo de sala pelo seu ID. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<UpdateStatus1Body, UpdateStatus1Parameters, TMeta, TSignal>, client?: (schema: UpdateStatus1Schema, options: ServiceOperationMutationFnOptions<UpdateStatus1Body, UpdateStatus1Parameters, TMeta, TSignal>) => Promise<RequestFnResponse<UpdateStatus1Data, UpdateStatus1Error>>): Promise<RequestFnResponse<UpdateStatus1Data, UpdateStatus1Error>>;
        /** @description Ativa ou desativa um tipo de sala pelo seu ID. */
        getMutationKey(parameters: DeepReadonly<UpdateStatus1Parameters> | void): ServiceOperationMutationKey<UpdateStatus1Schema, UpdateStatus1Parameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Ativa ou desativa um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateStatus1.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateStatus1.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends UpdateStatus1Body, TContext = unknown>(parameters: DeepReadonly<UpdateStatus1Parameters>, options?: ServiceOperationUseMutationOptions<UpdateStatus1Schema, UpdateStatus1Data, UpdateStatus1Parameters, TVariables, OperationError<UpdateStatus1Error>, TContext>): UseMutationResult<UpdateStatus1Data, OperationError<UpdateStatus1Error>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Ativa ou desativa um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateStatus1.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.updateStatus1.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<UpdateStatus1Body, UpdateStatus1Parameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<UpdateStatus1Schema, UpdateStatus1Data, UpdateStatus1Parameters, TVariables, OperationError<UpdateStatus1Error>, TContext>): UseMutationResult<UpdateStatus1Data, OperationError<UpdateStatus1Error>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Ativa ou desativa um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const updateStatus1Total = qraft.roomTypes.updateStatus1.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const updateStatus1Total = qraft.roomTypes.updateStatus1.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext> | MutationFiltersByMutationKey<UpdateStatus1Schema, UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Ativa ou desativa um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const updateStatus1PendingMutationVariables = qraft.roomTypes.updateStatus1.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const updateStatus1MutationData = qraft.roomTypes.updateStatus1.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<UpdateStatus1Data, OperationError<UpdateStatus1Error>, MutationVariables<UpdateStatus1Body, UpdateStatus1Parameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext> | MutationFiltersByMutationKey<UpdateStatus1Schema, UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext>;
            select?: (mutation: Mutation<UpdateStatus1Data, OperationError<UpdateStatus1Error>, MutationVariables<UpdateStatus1Body, UpdateStatus1Parameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Ativa ou desativa um tipo de sala pelo seu ID. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext> | MutationFiltersByMutationKey<UpdateStatus1Schema, UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Ativa ou desativa um tipo de sala pelo seu ID.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.roomTypes.updateStatus1.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.roomTypes.updateStatus1.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext> | MutationFiltersByMutationKey<UpdateStatus1Schema, UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext>): Mutation<UpdateStatus1Data, UpdateStatus1Error, MutationVariables<UpdateStatus1Body, UpdateStatus1Parameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext> | MutationFiltersByMutationKey<UpdateStatus1Schema, UpdateStatus1Body, UpdateStatus1Data, UpdateStatus1Parameters, OperationError<UpdateStatus1Error>, TContext>): Array<Mutation<UpdateStatus1Data, UpdateStatus1Error, MutationVariables<UpdateStatus1Body, UpdateStatus1Parameters>, TContext>>;
        };
        schema: UpdateStatus1Schema;
        types: {
            parameters: UpdateStatus1Parameters;
            data: UpdateStatus1Data;
            error: UpdateStatus1Error;
            body: UpdateStatus1Body;
        };
    };
    /** @description Retorna todos os tipos de sala cadastrados. */
    findAll2: {
        /** @description Retorna todos os tipos de sala cadastrados. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<FindAll2Schema, FindAll2Parameters, TMeta, TSignal> | (QueryFnOptionsByParameters<FindAll2Parameters, TMeta, TSignal> | void), client?: (schema: FindAll2Schema, options: {
            parameters: FindAll2Parameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<FindAll2Data, FindAll2Error>>): Promise<RequestFnResponse<FindAll2Data, FindAll2Error>>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getQueryKey(parameters: DeepReadonly<FindAll2Parameters> | void): ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.roomTypes.findAll2.useQuery()
         * ```
         */
        useQuery<TData = FindAll2Data>(parameters: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options?: Omit<UndefinedInitialDataOptions<FindAll2Data, FindAll2Error, TData, ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>>, "queryKey">): UseQueryResult<TData, OperationError<FindAll2Error>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.roomTypes.findAll2.useQuery()
         * ```
         */
        useQuery<TData = FindAll2Data>(parameters: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options: Omit<DefinedInitialDataOptions<FindAll2Data, FindAll2Error, TData, ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<FindAll2Error>>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getInfiniteQueryKey(parameters: DeepReadonly<FindAll2Parameters> | void): ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findAll2.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindAll2Parameters, TQueryFnData = FindAll2Data, TData = OperationInfiniteData<TQueryFnData, FindAll2Parameters>>(parameters: ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, FindAll2Error, TData, ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<FindAll2Error>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findAll2.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindAll2Parameters, TQueryFnData = FindAll2Data, TData = OperationInfiniteData<TQueryFnData, FindAll2Parameters>>(parameters: ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, FindAll2Error, TData, ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindAll2Data, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<FindAll2Error>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const findAll2Total = qraft.roomTypes.findAll2.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const findAll2Results = qraft.roomTypes.findAll2.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAll2Results.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const findAll2CombinedResults = qraft.roomTypes.findAll2.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAll2CombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<FindAll2Schema, FindAll2Parameters, FindAll2Data, FindAll2Error>>, TCombinedResult = Array<UseQueryResult<FindAll2Data, FindAll2Error>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<FindAll2Data, FindAll2Error>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.roomTypes.findAll2.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = FindAll2Data>(parameters: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options?: Omit<UseSuspenseQueryOptions<FindAll2Data, FindAll2Error, TData, ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<FindAll2Error>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.roomTypes.findAll2.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends FindAll2Parameters, TData = FindAll2Data>(parameters: ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<FindAll2Data, FindAll2Error, OperationInfiniteData<TData, FindAll2Parameters>, ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindAll2Data, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, FindAll2Parameters>, OperationError<FindAll2Error>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @description Retorna todos os tipos de sala cadastrados.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const findAll2Data = qraft.roomTypes.findAll2.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAll2Results.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const findAll2CombinedData = qraft.roomTypes.findAll2.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAll2CombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<FindAll2Schema, FindAll2Parameters, FindAll2Data, FindAll2Error>>, TCombinedResult = Array<UseSuspenseQueryResult<FindAll2Data, FindAll2Error>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<FindAll2Data, FindAll2Error>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @description Retorna todos os tipos de sala cadastrados. */
        fetchQuery(options: ServiceOperationFetchQueryOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, FindAll2Error> | void): Promise<FindAll2Data>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, FindAll2Error> | void): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, FindAll2Error> | void): Promise<FindAll2Data>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        fetchInfiniteQuery<TPageParam extends FindAll2Parameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, DeepReadonly<TPageParam>, FindAll2Error> | void): Promise<OperationInfiniteData<FindAll2Data, FindAll2Parameters>>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        prefetchInfiniteQuery<TPageParam extends FindAll2Parameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, DeepReadonly<TPageParam>, FindAll2Error> | void): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        ensureInfiniteQueryData<TPageParam extends FindAll2Parameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<FindAll2Schema, FindAll2Data, FindAll2Parameters, DeepReadonly<TPageParam>, FindAll2Error> | void): Promise<OperationInfiniteData<FindAll2Data, FindAll2Parameters>>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getQueryData(parameters: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void)): FindAll2Data | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void)): OperationInfiniteData<FindAll2Data, FindAll2Parameters> | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>,
            data: NoInfer<OperationInfiniteData<FindAll2Data, FindAll2Parameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>,
            data: FindAll2Data | undefined
        ]>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getQueryState(parameters: ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters> | (DeepReadonly<FindAll2Parameters> | void)): QueryState<FindAll2Data, FindAll2Error> | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        getInfiniteQueryState(parameters: DeepReadonly<FindAll2Parameters> | ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters> | void): QueryState<OperationInfiniteData<FindAll2Data, FindAll2Parameters>, FindAll2Error> | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        setQueryData(parameters: (DeepReadonly<FindAll2Parameters> | undefined) | ServiceOperationQueryKey<FindAll2Schema, FindAll2Parameters>, updater: Updater<NoInfer<FindAll2Data> | undefined, NoInfer<DeepReadonly<FindAll2Data>> | undefined>, options?: SetDataOptions): FindAll2Data | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        setInfiniteQueryData(parameters: (DeepReadonly<FindAll2Parameters> | undefined) | ServiceOperationInfiniteQueryKey<FindAll2Schema, FindAll2Parameters>, updater: Updater<NoInfer<OperationInfiniteData<FindAll2Data, FindAll2Parameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<FindAll2Data, FindAll2Parameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<FindAll2Data, FindAll2Parameters> | undefined;
        /** @description Retorna todos os tipos de sala cadastrados. */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>, updater: Updater<NoInfer<FindAll2Data> | undefined, NoInfer<FindAll2Data> | undefined>, options?: SetDataOptions): Array<FindAll2Data | undefined>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>, options?: InvalidateOptions): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>, options?: RefetchOptions): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>, options?: CancelOptions): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>): void;
        /** @description Retorna todos os tipos de sala cadastrados. */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>, options?: ResetOptions): Promise<void>;
        /** @description Retorna todos os tipos de sala cadastrados. */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error> | QueryFiltersByQueryKey<FindAll2Schema, FindAll2Data, TInfinite, FindAll2Parameters, FindAll2Error>): number;
        schema: FindAll2Schema;
        types: {
            parameters: FindAll2Parameters;
            data: FindAll2Data;
            error: FindAll2Error;
        };
    };
    /** @description Cadastra um novo tipo de sala. */
    create2: {
        /** @description Cadastra um novo tipo de sala. */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<Create2Body, Create2Parameters, TMeta, TSignal>, client?: (schema: Create2Schema, options: ServiceOperationMutationFnOptions<Create2Body, Create2Parameters, TMeta, TSignal>) => Promise<RequestFnResponse<Create2Data, Create2Error>>): Promise<RequestFnResponse<Create2Data, Create2Error>>;
        /** @description Cadastra um novo tipo de sala. */
        getMutationKey(parameters: DeepReadonly<Create2Parameters> | void): ServiceOperationMutationKey<Create2Schema, Create2Parameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Cadastra um novo tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.create2.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.create2.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends Create2Body, TContext = unknown>(parameters: DeepReadonly<Create2Parameters>, options?: ServiceOperationUseMutationOptions<Create2Schema, Create2Data, Create2Parameters, TVariables, OperationError<Create2Error>, TContext>): UseMutationResult<Create2Data, OperationError<Create2Error>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @description Cadastra um novo tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.create2.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.roomTypes.create2.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<Create2Body, Create2Parameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<Create2Schema, Create2Data, Create2Parameters, TVariables, OperationError<Create2Error>, TContext>): UseMutationResult<Create2Data, OperationError<Create2Error>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @description Cadastra um novo tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const create2Total = qraft.roomTypes.create2.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const create2Total = qraft.roomTypes.create2.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext> | MutationFiltersByMutationKey<Create2Schema, Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @description Cadastra um novo tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const create2PendingMutationVariables = qraft.roomTypes.create2.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const create2MutationData = qraft.roomTypes.create2.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<Create2Data, OperationError<Create2Error>, MutationVariables<Create2Body, Create2Parameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext> | MutationFiltersByMutationKey<Create2Schema, Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext>;
            select?: (mutation: Mutation<Create2Data, OperationError<Create2Error>, MutationVariables<Create2Body, Create2Parameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @description Cadastra um novo tipo de sala. */
        isMutating<TContext>(filters?: MutationFiltersByParameters<Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext> | MutationFiltersByMutationKey<Create2Schema, Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @description Cadastra um novo tipo de sala.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.roomTypes.create2.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.roomTypes.create2.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext> | MutationFiltersByMutationKey<Create2Schema, Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext>): Mutation<Create2Data, Create2Error, MutationVariables<Create2Body, Create2Parameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext> | MutationFiltersByMutationKey<Create2Schema, Create2Body, Create2Data, Create2Parameters, OperationError<Create2Error>, TContext>): Array<Mutation<Create2Data, Create2Error, MutationVariables<Create2Body, Create2Parameters>, TContext>>;
        };
        schema: Create2Schema;
        types: {
            parameters: Create2Parameters;
            data: Create2Data;
            error: Create2Error;
            body: Create2Body;
        };
    };
}
/** @description Retorna os dados de um tipo de sala pelo seu ID. */
export const findById2 = {
    schema: {
        method: "get",
        url: "/room-types/{id}"
    }
} as {
    schema: FindById2Schema;
    [QraftServiceOperationsToken]: RoomTypesService["findById2"];
};
/** @description Atualiza os dados de um tipo de sala. */
export const updateById1 = {
    schema: {
        method: "put",
        url: "/room-types/{id}",
        mediaType: ["application/json"]
    }
} as {
    schema: UpdateById1Schema;
    [QraftServiceOperationsToken]: RoomTypesService["updateById1"];
};
/** @description Desativa um tipo de sala pelo seu ID (soft delete). */
export const deleteById2 = {
    schema: {
        method: "delete",
        url: "/room-types/{id}"
    }
} as {
    schema: DeleteById2Schema;
    [QraftServiceOperationsToken]: RoomTypesService["deleteById2"];
};
/** @description Ativa ou desativa um tipo de sala pelo seu ID. */
export const updateStatus1 = {
    schema: {
        method: "patch",
        url: "/room-types/{id}",
        mediaType: ["application/json"]
    }
} as {
    schema: UpdateStatus1Schema;
    [QraftServiceOperationsToken]: RoomTypesService["updateStatus1"];
};
/** @description Retorna todos os tipos de sala cadastrados. */
export const findAll2 = {
    schema: {
        method: "get",
        url: "/room-types"
    }
} as {
    schema: FindAll2Schema;
    [QraftServiceOperationsToken]: RoomTypesService["findAll2"];
};
/** @description Cadastra um novo tipo de sala. */
export const create2 = {
    schema: {
        method: "post",
        url: "/room-types",
        mediaType: ["application/json"]
    }
} as {
    schema: Create2Schema;
    [QraftServiceOperationsToken]: RoomTypesService["create2"];
};
export const roomTypesService = {
    findById2,
    updateById1,
    deleteById2,
    updateStatus1,
    findAll2,
    create2
} as const;
type FindById2Schema = {
    method: "get";
    url: "/room-types/{id}";
};
type FindById2Parameters = paths["/room-types/{id}"]["get"]["parameters"];
type FindById2Data = paths["/room-types/{id}"]["get"]["responses"]["200"]["content"]["*/*"];
type FindById2Error = paths["/room-types/{id}"]["get"]["responses"]["400"]["content"]["*/*"] | paths["/room-types/{id}"]["get"]["responses"]["404"]["content"]["*/*"] | paths["/room-types/{id}"]["get"]["responses"]["409"]["content"]["*/*"] | paths["/room-types/{id}"]["get"]["responses"]["422"]["content"]["*/*"];
type UpdateById1Schema = {
    method: "put";
    url: "/room-types/{id}";
    mediaType: [
        "application/json"
    ];
};
type UpdateById1Parameters = paths["/room-types/{id}"]["put"]["parameters"];
type UpdateById1Data = paths["/room-types/{id}"]["put"]["responses"]["200"]["content"]["*/*"];
type UpdateById1Error = paths["/room-types/{id}"]["put"]["responses"]["400"]["content"]["*/*"] | paths["/room-types/{id}"]["put"]["responses"]["404"]["content"]["*/*"] | paths["/room-types/{id}"]["put"]["responses"]["409"]["content"]["*/*"] | paths["/room-types/{id}"]["put"]["responses"]["422"]["content"]["*/*"];
type UpdateById1Body = paths["/room-types/{id}"]["put"]["requestBody"]["content"]["application/json"];
type DeleteById2Schema = {
    method: "delete";
    url: "/room-types/{id}";
};
type DeleteById2Parameters = paths["/room-types/{id}"]["delete"]["parameters"];
type DeleteById2Data = null;
type DeleteById2Error = paths["/room-types/{id}"]["delete"]["responses"]["400"]["content"]["*/*"] | paths["/room-types/{id}"]["delete"]["responses"]["404"]["content"]["*/*"] | paths["/room-types/{id}"]["delete"]["responses"]["409"]["content"]["*/*"] | paths["/room-types/{id}"]["delete"]["responses"]["422"]["content"]["*/*"];
type DeleteById2Body = undefined;
type UpdateStatus1Schema = {
    method: "patch";
    url: "/room-types/{id}";
    mediaType: [
        "application/json"
    ];
};
type UpdateStatus1Parameters = paths["/room-types/{id}"]["patch"]["parameters"];
type UpdateStatus1Data = paths["/room-types/{id}"]["patch"]["responses"]["200"]["content"]["*/*"];
type UpdateStatus1Error = paths["/room-types/{id}"]["patch"]["responses"]["400"]["content"]["*/*"] | paths["/room-types/{id}"]["patch"]["responses"]["404"]["content"]["*/*"] | paths["/room-types/{id}"]["patch"]["responses"]["409"]["content"]["*/*"] | paths["/room-types/{id}"]["patch"]["responses"]["422"]["content"]["*/*"];
type UpdateStatus1Body = paths["/room-types/{id}"]["patch"]["requestBody"]["content"]["application/json"];
type FindAll2Schema = {
    method: "get";
    url: "/room-types";
};
type FindAll2Parameters = undefined;
type FindAll2Data = paths["/room-types"]["get"]["responses"]["200"]["content"]["*/*"];
type FindAll2Error = paths["/room-types"]["get"]["responses"]["400"]["content"]["*/*"] | paths["/room-types"]["get"]["responses"]["404"]["content"]["*/*"] | paths["/room-types"]["get"]["responses"]["409"]["content"]["*/*"] | paths["/room-types"]["get"]["responses"]["422"]["content"]["*/*"];
type Create2Schema = {
    method: "post";
    url: "/room-types";
    mediaType: [
        "application/json"
    ];
};
type Create2Parameters = {
    query?: never;
    header?: never;
    path?: never;
};
type Create2Data = paths["/room-types"]["post"]["responses"]["201"]["content"]["*/*"];
type Create2Error = paths["/room-types"]["post"]["responses"]["400"]["content"]["*/*"] | paths["/room-types"]["post"]["responses"]["404"]["content"]["*/*"] | paths["/room-types"]["post"]["responses"]["409"]["content"]["*/*"] | paths["/room-types"]["post"]["responses"]["422"]["content"]["*/*"];
type Create2Body = paths["/room-types"]["post"]["requestBody"]["content"]["application/json"];
