/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationCache, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface UsersService {
    findById: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<FindByIdSchema, FindByIdParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<FindByIdParameters, TMeta, TSignal>), client?: (schema: FindByIdSchema, options: {
            parameters: FindByIdParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<FindByIdData, FindByIdError>>): Promise<RequestFnResponse<FindByIdData, FindByIdError>>;
        /**/
        getQueryKey(parameters: DeepReadonly<FindByIdParameters>): ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.users.findById.useQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useQuery<TData = FindByIdData>(parameters: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options?: Omit<UndefinedInitialDataOptions<FindByIdData, FindByIdError, TData, ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>>, "queryKey">): UseQueryResult<TData, OperationError<FindByIdError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.users.findById.useQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useQuery<TData = FindByIdData>(parameters: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options: Omit<DefinedInitialDataOptions<FindByIdData, FindByIdError, TData, ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<FindByIdError>>;
        /**/
        getInfiniteQueryKey(parameters: DeepReadonly<FindByIdParameters>): ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findById.useInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindByIdParameters, TQueryFnData = FindByIdData, TData = OperationInfiniteData<TQueryFnData, FindByIdParameters>>(parameters: ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, FindByIdError, TData, ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<FindByIdError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findById.useInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindByIdParameters, TQueryFnData = FindByIdData, TData = OperationInfiniteData<TQueryFnData, FindByIdParameters>>(parameters: ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, FindByIdError, TData, ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindByIdData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<FindByIdError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const findByIdTotal = qraft.users.findById.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const findByIdByParametersTotal = qraft.users.findById.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const findByIdResults = qraft.users.findById.useQueries({
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findByIdResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const findByIdCombinedResults = qraft.users.findById.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findByIdCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<FindByIdSchema, FindByIdParameters, FindByIdData, FindByIdError>>, TCombinedResult = Array<UseQueryResult<FindByIdData, FindByIdError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<FindByIdData, FindByIdError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.users.findById.useSuspenseQuery({
         *     path: {
         *         id: id
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = FindByIdData>(parameters: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options?: Omit<UseSuspenseQueryOptions<FindByIdData, FindByIdError, TData, ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<FindByIdError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findById.useSuspenseInfiniteQuery({
         *     path: {
         *         id: id
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends FindByIdParameters, TData = FindByIdData>(parameters: ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>), options: Omit<UseSuspenseInfiniteQueryOptions<FindByIdData, FindByIdError, OperationInfiniteData<TData, FindByIdParameters>, ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindByIdData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, FindByIdParameters>, OperationError<FindByIdError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const findByIdData = qraft.users.findById.useSuspenseQueries({
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findByIdResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const findByIdCombinedData = qraft.users.findById.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 id: id1
         *             }
         *         },
         *         {
         *             path: {
         *                 id: id2
         *             }
         *         }
         *     ]
         * });
         * findByIdCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<FindByIdSchema, FindByIdParameters, FindByIdData, FindByIdError>>, TCombinedResult = Array<UseSuspenseQueryResult<FindByIdData, FindByIdError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<FindByIdData, FindByIdError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**/
        fetchQuery(options: ServiceOperationFetchQueryOptions<FindByIdSchema, FindByIdData, FindByIdParameters, FindByIdError>): Promise<FindByIdData>;
        /**/
        prefetchQuery(options: ServiceOperationFetchQueryOptions<FindByIdSchema, FindByIdData, FindByIdParameters, FindByIdError>): Promise<void>;
        /**/
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<FindByIdSchema, FindByIdData, FindByIdParameters, FindByIdError>): Promise<FindByIdData>;
        /**/
        fetchInfiniteQuery<TPageParam extends FindByIdParameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindByIdSchema, FindByIdData, FindByIdParameters, DeepReadonly<TPageParam>, FindByIdError>): Promise<OperationInfiniteData<FindByIdData, FindByIdParameters>>;
        /**/
        prefetchInfiniteQuery<TPageParam extends FindByIdParameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindByIdSchema, FindByIdData, FindByIdParameters, DeepReadonly<TPageParam>, FindByIdError>): Promise<void>;
        /**/
        ensureInfiniteQueryData<TPageParam extends FindByIdParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<FindByIdSchema, FindByIdData, FindByIdParameters, DeepReadonly<TPageParam>, FindByIdError>): Promise<OperationInfiniteData<FindByIdData, FindByIdParameters>>;
        /**/
        getQueryData(parameters: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>)): FindByIdData | undefined;
        /**/
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>)): OperationInfiniteData<FindByIdData, FindByIdParameters> | undefined;
        /**/
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>,
            data: NoInfer<OperationInfiniteData<FindByIdData, FindByIdParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>,
            data: FindByIdData | undefined
        ]>;
        /**/
        getQueryState(parameters: ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters> | (DeepReadonly<FindByIdParameters>)): QueryState<FindByIdData, FindByIdError> | undefined;
        /**/
        getInfiniteQueryState(parameters: DeepReadonly<FindByIdParameters> | ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>): QueryState<OperationInfiniteData<FindByIdData, FindByIdParameters>, FindByIdError> | undefined;
        /**/
        setQueryData(parameters: (DeepReadonly<FindByIdParameters>) | ServiceOperationQueryKey<FindByIdSchema, FindByIdParameters>, updater: Updater<NoInfer<FindByIdData> | undefined, NoInfer<DeepReadonly<FindByIdData>> | undefined>, options?: SetDataOptions): FindByIdData | undefined;
        /**/
        setInfiniteQueryData(parameters: (DeepReadonly<FindByIdParameters>) | ServiceOperationInfiniteQueryKey<FindByIdSchema, FindByIdParameters>, updater: Updater<NoInfer<OperationInfiniteData<FindByIdData, FindByIdParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<FindByIdData, FindByIdParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<FindByIdData, FindByIdParameters> | undefined;
        /**/
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>, updater: Updater<NoInfer<FindByIdData> | undefined, NoInfer<FindByIdData> | undefined>, options?: SetDataOptions): Array<FindByIdData | undefined>;
        /**/
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>, options?: InvalidateOptions): Promise<void>;
        /**/
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>, options?: RefetchOptions): Promise<void>;
        /**/
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>, options?: CancelOptions): Promise<void>;
        /**/
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>): void;
        /**/
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>, options?: ResetOptions): Promise<void>;
        /**/
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError> | QueryFiltersByQueryKey<FindByIdSchema, FindByIdData, TInfinite, FindByIdParameters, FindByIdError>): number;
        schema: FindByIdSchema;
        types: {
            parameters: FindByIdParameters;
            data: FindByIdData;
            error: FindByIdError;
        };
    };
    update: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<UpdateBody, UpdateParameters, TMeta, TSignal>, client?: (schema: UpdateSchema, options: ServiceOperationMutationFnOptions<UpdateBody, UpdateParameters, TMeta, TSignal>) => Promise<RequestFnResponse<UpdateData, UpdateError>>): Promise<RequestFnResponse<UpdateData, UpdateError>>;
        /**/
        getMutationKey(parameters: DeepReadonly<UpdateParameters> | void): ServiceOperationMutationKey<UpdateSchema, UpdateParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.update.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.update.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends UpdateBody, TContext = unknown>(parameters: DeepReadonly<UpdateParameters>, options?: ServiceOperationUseMutationOptions<UpdateSchema, UpdateData, UpdateParameters, TVariables, OperationError<UpdateError>, TContext>): UseMutationResult<UpdateData, OperationError<UpdateError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.update.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.update.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<UpdateBody, UpdateParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<UpdateSchema, UpdateData, UpdateParameters, TVariables, OperationError<UpdateError>, TContext>): UseMutationResult<UpdateData, OperationError<UpdateError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const updateTotal = qraft.users.update.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const updateTotal = qraft.users.update.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext> | MutationFiltersByMutationKey<UpdateSchema, UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const updatePendingMutationVariables = qraft.users.update.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const updateMutationData = qraft.users.update.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<UpdateData, OperationError<UpdateError>, MutationVariables<UpdateBody, UpdateParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext> | MutationFiltersByMutationKey<UpdateSchema, UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext>;
            select?: (mutation: Mutation<UpdateData, OperationError<UpdateError>, MutationVariables<UpdateBody, UpdateParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /**/
        isMutating<TContext>(filters?: MutationFiltersByParameters<UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext> | MutationFiltersByMutationKey<UpdateSchema, UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.users.update.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.users.update.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext> | MutationFiltersByMutationKey<UpdateSchema, UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext>): Mutation<UpdateData, UpdateError, MutationVariables<UpdateBody, UpdateParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext> | MutationFiltersByMutationKey<UpdateSchema, UpdateBody, UpdateData, UpdateParameters, OperationError<UpdateError>, TContext>): Array<Mutation<UpdateData, UpdateError, MutationVariables<UpdateBody, UpdateParameters>, TContext>>;
        };
        schema: UpdateSchema;
        types: {
            parameters: UpdateParameters;
            data: UpdateData;
            error: UpdateError;
            body: UpdateBody;
        };
    };
    delete: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<DeleteBody, DeleteParameters, TMeta, TSignal>, client?: (schema: DeleteSchema, options: ServiceOperationMutationFnOptions<DeleteBody, DeleteParameters, TMeta, TSignal>) => Promise<RequestFnResponse<DeleteData, DeleteError>>): Promise<RequestFnResponse<DeleteData, DeleteError>>;
        /**/
        getMutationKey(parameters: DeepReadonly<DeleteParameters> | void): ServiceOperationMutationKey<DeleteSchema, DeleteParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.delete.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.delete.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends DeleteBody, TContext = unknown>(parameters: DeepReadonly<DeleteParameters>, options?: ServiceOperationUseMutationOptions<DeleteSchema, DeleteData, DeleteParameters, TVariables, OperationError<DeleteError>, TContext>): UseMutationResult<DeleteData, OperationError<DeleteError>, TVariables | void, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.delete.useMutation({
         *     path: {
         *         id: id
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.delete.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     path: {
         *         id: id
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<DeleteBody, DeleteParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<DeleteSchema, DeleteData, DeleteParameters, TVariables, OperationError<DeleteError>, TContext>): UseMutationResult<DeleteData, OperationError<DeleteError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const deleteTotal = qraft.users.delete.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const deleteTotal = qraft.users.delete.useIsMutating({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext> | MutationFiltersByMutationKey<DeleteSchema, DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const deletePendingMutationVariables = qraft.users.delete.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const deleteMutationData = qraft.users.delete.useMutationState({
         *     filters: {
         *         parameters: {
         *             path: {
         *                 id: id
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<DeleteData, OperationError<DeleteError>, MutationVariables<DeleteBody, DeleteParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext> | MutationFiltersByMutationKey<DeleteSchema, DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext>;
            select?: (mutation: Mutation<DeleteData, OperationError<DeleteError>, MutationVariables<DeleteBody, DeleteParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /**/
        isMutating<TContext>(filters?: MutationFiltersByParameters<DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext> | MutationFiltersByMutationKey<DeleteSchema, DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.users.delete.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         path: {
         *             id: id
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.users.delete.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext> | MutationFiltersByMutationKey<DeleteSchema, DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext>): Mutation<DeleteData, DeleteError, MutationVariables<DeleteBody, DeleteParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext> | MutationFiltersByMutationKey<DeleteSchema, DeleteBody, DeleteData, DeleteParameters, OperationError<DeleteError>, TContext>): Array<Mutation<DeleteData, DeleteError, MutationVariables<DeleteBody, DeleteParameters>, TContext>>;
        };
        schema: DeleteSchema;
        types: {
            parameters: DeleteParameters;
            data: DeleteData;
            error: DeleteError;
            body: DeleteBody;
        };
    };
    findAll: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<FindAllSchema, FindAllParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<FindAllParameters, TMeta, TSignal> | void), client?: (schema: FindAllSchema, options: {
            parameters: FindAllParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<FindAllData, FindAllError>>): Promise<RequestFnResponse<FindAllData, FindAllError>>;
        /**/
        getQueryKey(parameters: DeepReadonly<FindAllParameters> | void): ServiceOperationQueryKey<FindAllSchema, FindAllParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.users.findAll.useQuery()
         * ```
         */
        useQuery<TData = FindAllData>(parameters: ServiceOperationQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options?: Omit<UndefinedInitialDataOptions<FindAllData, FindAllError, TData, ServiceOperationQueryKey<FindAllSchema, FindAllParameters>>, "queryKey">): UseQueryResult<TData, OperationError<FindAllError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.users.findAll.useQuery()
         * ```
         */
        useQuery<TData = FindAllData>(parameters: ServiceOperationQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options: Omit<DefinedInitialDataOptions<FindAllData, FindAllError, TData, ServiceOperationQueryKey<FindAllSchema, FindAllParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<FindAllError>>;
        /**/
        getInfiniteQueryKey(parameters: DeepReadonly<FindAllParameters> | void): ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findAll.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindAllParameters, TQueryFnData = FindAllData, TData = OperationInfiniteData<TQueryFnData, FindAllParameters>>(parameters: ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, FindAllError, TData, ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<FindAllError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findAll.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends FindAllParameters, TQueryFnData = FindAllData, TData = OperationInfiniteData<TQueryFnData, FindAllParameters>>(parameters: ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, FindAllError, TData, ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindAllData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<FindAllError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const findAllTotal = qraft.users.findAll.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const findAllResults = qraft.users.findAll.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAllResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const findAllCombinedResults = qraft.users.findAll.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAllCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<FindAllSchema, FindAllParameters, FindAllData, FindAllError>>, TCombinedResult = Array<UseQueryResult<FindAllData, FindAllError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<FindAllData, FindAllError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.users.findAll.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = FindAllData>(parameters: ServiceOperationQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options?: Omit<UseSuspenseQueryOptions<FindAllData, FindAllError, TData, ServiceOperationQueryKey<FindAllSchema, FindAllParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<FindAllError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.users.findAll.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends FindAllParameters, TData = FindAllData>(parameters: ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<FindAllData, FindAllError, OperationInfiniteData<TData, FindAllParameters>, ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<FindAllData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, FindAllParameters>, OperationError<FindAllError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const findAllData = qraft.users.findAll.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAllResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const findAllCombinedData = qraft.users.findAll.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * findAllCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<FindAllSchema, FindAllParameters, FindAllData, FindAllError>>, TCombinedResult = Array<UseSuspenseQueryResult<FindAllData, FindAllError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<FindAllData, FindAllError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**/
        fetchQuery(options: ServiceOperationFetchQueryOptions<FindAllSchema, FindAllData, FindAllParameters, FindAllError> | void): Promise<FindAllData>;
        /**/
        prefetchQuery(options: ServiceOperationFetchQueryOptions<FindAllSchema, FindAllData, FindAllParameters, FindAllError> | void): Promise<void>;
        /**/
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<FindAllSchema, FindAllData, FindAllParameters, FindAllError> | void): Promise<FindAllData>;
        /**/
        fetchInfiniteQuery<TPageParam extends FindAllParameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindAllSchema, FindAllData, FindAllParameters, DeepReadonly<TPageParam>, FindAllError> | void): Promise<OperationInfiniteData<FindAllData, FindAllParameters>>;
        /**/
        prefetchInfiniteQuery<TPageParam extends FindAllParameters>(options: ServiceOperationFetchInfiniteQueryOptions<FindAllSchema, FindAllData, FindAllParameters, DeepReadonly<TPageParam>, FindAllError> | void): Promise<void>;
        /**/
        ensureInfiniteQueryData<TPageParam extends FindAllParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<FindAllSchema, FindAllData, FindAllParameters, DeepReadonly<TPageParam>, FindAllError> | void): Promise<OperationInfiniteData<FindAllData, FindAllParameters>>;
        /**/
        getQueryData(parameters: ServiceOperationQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void)): FindAllData | undefined;
        /**/
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void)): OperationInfiniteData<FindAllData, FindAllParameters> | undefined;
        /**/
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>,
            data: NoInfer<OperationInfiniteData<FindAllData, FindAllParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<FindAllSchema, FindAllParameters>,
            data: FindAllData | undefined
        ]>;
        /**/
        getQueryState(parameters: ServiceOperationQueryKey<FindAllSchema, FindAllParameters> | (DeepReadonly<FindAllParameters> | void)): QueryState<FindAllData, FindAllError> | undefined;
        /**/
        getInfiniteQueryState(parameters: DeepReadonly<FindAllParameters> | ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters> | void): QueryState<OperationInfiniteData<FindAllData, FindAllParameters>, FindAllError> | undefined;
        /**/
        setQueryData(parameters: (DeepReadonly<FindAllParameters> | undefined) | ServiceOperationQueryKey<FindAllSchema, FindAllParameters>, updater: Updater<NoInfer<FindAllData> | undefined, NoInfer<DeepReadonly<FindAllData>> | undefined>, options?: SetDataOptions): FindAllData | undefined;
        /**/
        setInfiniteQueryData(parameters: (DeepReadonly<FindAllParameters> | undefined) | ServiceOperationInfiniteQueryKey<FindAllSchema, FindAllParameters>, updater: Updater<NoInfer<OperationInfiniteData<FindAllData, FindAllParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<FindAllData, FindAllParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<FindAllData, FindAllParameters> | undefined;
        /**/
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>, updater: Updater<NoInfer<FindAllData> | undefined, NoInfer<FindAllData> | undefined>, options?: SetDataOptions): Array<FindAllData | undefined>;
        /**/
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>, options?: InvalidateOptions): Promise<void>;
        /**/
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>, options?: RefetchOptions): Promise<void>;
        /**/
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>, options?: CancelOptions): Promise<void>;
        /**/
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>): void;
        /**/
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>, options?: ResetOptions): Promise<void>;
        /**/
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError> | QueryFiltersByQueryKey<FindAllSchema, FindAllData, TInfinite, FindAllParameters, FindAllError>): number;
        schema: FindAllSchema;
        types: {
            parameters: FindAllParameters;
            data: FindAllData;
            error: FindAllError;
        };
    };
    create: {
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<CreateBody, CreateParameters, TMeta, TSignal>, client?: (schema: CreateSchema, options: ServiceOperationMutationFnOptions<CreateBody, CreateParameters, TMeta, TSignal>) => Promise<RequestFnResponse<CreateData, CreateError>>): Promise<RequestFnResponse<CreateData, CreateError>>;
        /**/
        getMutationKey(parameters: DeepReadonly<CreateParameters> | void): ServiceOperationMutationKey<CreateSchema, CreateParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.create.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.create.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends CreateBody, TContext = unknown>(parameters: DeepReadonly<CreateParameters>, options?: ServiceOperationUseMutationOptions<CreateSchema, CreateData, CreateParameters, TVariables, OperationError<CreateError>, TContext>): UseMutationResult<CreateData, OperationError<CreateError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.users.create.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.users.create.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<CreateBody, CreateParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<CreateSchema, CreateData, CreateParameters, TVariables, OperationError<CreateError>, TContext>): UseMutationResult<CreateData, OperationError<CreateError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const createTotal = qraft.users.create.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const createTotal = qraft.users.create.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const createPendingMutationVariables = qraft.users.create.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const createMutationData = qraft.users.create.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<CreateData, OperationError<CreateError>, MutationVariables<CreateBody, CreateParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext>;
            select?: (mutation: Mutation<CreateData, OperationError<CreateError>, MutationVariables<CreateBody, CreateParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /**/
        isMutating<TContext>(filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.users.create.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.users.create.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext>): Mutation<CreateData, CreateError, MutationVariables<CreateBody, CreateParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, OperationError<CreateError>, TContext>): Array<Mutation<CreateData, CreateError, MutationVariables<CreateBody, CreateParameters>, TContext>>;
        };
        schema: CreateSchema;
        types: {
            parameters: CreateParameters;
            data: CreateData;
            error: CreateError;
            body: CreateBody;
        };
    };
}
export const findById = {
    schema: {
        method: "get",
        url: "/users/{id}"
    }
} as {
    schema: FindByIdSchema;
    [QraftServiceOperationsToken]: UsersService["findById"];
};
export const update = {
    schema: {
        method: "put",
        url: "/users/{id}",
        mediaType: ["application/json"]
    }
} as {
    schema: UpdateSchema;
    [QraftServiceOperationsToken]: UsersService["update"];
};
export const ddelete = {
    schema: {
        method: "delete",
        url: "/users/{id}"
    }
} as {
    schema: DeleteSchema;
    [QraftServiceOperationsToken]: UsersService["delete"];
};
export const findAll = {
    schema: {
        method: "get",
        url: "/users"
    }
} as {
    schema: FindAllSchema;
    [QraftServiceOperationsToken]: UsersService["findAll"];
};
export const create = {
    schema: {
        method: "post",
        url: "/users",
        mediaType: ["application/json"]
    }
} as {
    schema: CreateSchema;
    [QraftServiceOperationsToken]: UsersService["create"];
};
export const usersService = {
    findById,
    update,
    ddelete,
    findAll,
    create
} as const;
type FindByIdSchema = {
    method: "get";
    url: "/users/{id}";
};
type FindByIdParameters = paths["/users/{id}"]["get"]["parameters"];
type FindByIdData = paths["/users/{id}"]["get"]["responses"]["200"]["content"]["*/*"];
type FindByIdError = unknown;
type UpdateSchema = {
    method: "put";
    url: "/users/{id}";
    mediaType: [
        "application/json"
    ];
};
type UpdateParameters = paths["/users/{id}"]["put"]["parameters"];
type UpdateData = paths["/users/{id}"]["put"]["responses"]["200"]["content"]["*/*"];
type UpdateError = unknown;
type UpdateBody = paths["/users/{id}"]["put"]["requestBody"]["content"]["application/json"];
type DeleteSchema = {
    method: "delete";
    url: "/users/{id}";
};
type DeleteParameters = paths["/users/{id}"]["delete"]["parameters"];
type DeleteData = null;
type DeleteError = unknown;
type DeleteBody = undefined;
type FindAllSchema = {
    method: "get";
    url: "/users";
};
type FindAllParameters = undefined;
type FindAllData = paths["/users"]["get"]["responses"]["200"]["content"]["*/*"];
type FindAllError = unknown;
type CreateSchema = {
    method: "post";
    url: "/users";
    mediaType: [
        "application/json"
    ];
};
type CreateParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type CreateData = paths["/users"]["post"]["responses"]["201"]["content"]["*/*"];
type CreateError = unknown;
type CreateBody = paths["/users"]["post"]["requestBody"]["content"]["application/json"];
