/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedRoomsRouteRouteImport } from './routes/_authenticated/rooms/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSolicitacoesIndexRouteImport } from './routes/_authenticated/solicitacoes/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms/index'
import { Route as AuthenticatedGradeIndexRouteImport } from './routes/_authenticated/grade/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedBuscarSalaIndexRouteImport } from './routes/_authenticated/buscar-sala/index'
import { Route as AuthenticatedRoomsRoomTypesIndexRouteImport } from './routes/_authenticated/rooms/room-types/index'
import { Route as AuthenticatedRoomsResourcesIndexRouteImport } from './routes/_authenticated/rooms/resources/index'
import { Route as AuthenticatedRoomsBuildingsIndexRouteImport } from './routes/_authenticated/rooms/buildings/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsRouteRoute = AuthenticatedRoomsRouteRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesIndexRoute =
  AuthenticatedSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoomsRouteRoute,
} as any)
const AuthenticatedGradeIndexRoute = AuthenticatedGradeIndexRouteImport.update({
  id: '/grade/',
  path: '/grade/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuscarSalaIndexRoute =
  AuthenticatedBuscarSalaIndexRouteImport.update({
    id: '/buscar-sala/',
    path: '/buscar-sala/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoomTypesIndexRoute =
  AuthenticatedRoomsRoomTypesIndexRouteImport.update({
    id: '/room-types/',
    path: '/room-types/',
    getParentRoute: () => AuthenticatedRoomsRouteRoute,
  } as any)
const AuthenticatedRoomsResourcesIndexRoute =
  AuthenticatedRoomsResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthenticatedRoomsRouteRoute,
  } as any)
const AuthenticatedRoomsBuildingsIndexRoute =
  AuthenticatedRoomsBuildingsIndexRouteImport.update({
    id: '/buildings/',
    path: '/buildings/',
    getParentRoute: () => AuthenticatedRoomsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms': typeof AuthenticatedRoomsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/buscar-sala/': typeof AuthenticatedBuscarSalaIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/grade/': typeof AuthenticatedGradeIndexRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/rooms/buildings/': typeof AuthenticatedRoomsBuildingsIndexRoute
  '/rooms/resources/': typeof AuthenticatedRoomsResourcesIndexRoute
  '/rooms/room-types/': typeof AuthenticatedRoomsRoomTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/buscar-sala': typeof AuthenticatedBuscarSalaIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/grade': typeof AuthenticatedGradeIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/rooms/buildings': typeof AuthenticatedRoomsBuildingsIndexRoute
  '/rooms/resources': typeof AuthenticatedRoomsResourcesIndexRoute
  '/rooms/room-types': typeof AuthenticatedRoomsRoomTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/rooms': typeof AuthenticatedRoomsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/buscar-sala/': typeof AuthenticatedBuscarSalaIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/grade/': typeof AuthenticatedGradeIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/rooms/buildings/': typeof AuthenticatedRoomsBuildingsIndexRoute
  '/_authenticated/rooms/resources/': typeof AuthenticatedRoomsResourcesIndexRoute
  '/_authenticated/rooms/room-types/': typeof AuthenticatedRoomsRoomTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rooms'
    | '/login/'
    | '/buscar-sala/'
    | '/dashboard/'
    | '/grade/'
    | '/rooms/'
    | '/settings/'
    | '/solicitacoes/'
    | '/users/'
    | '/rooms/buildings/'
    | '/rooms/resources/'
    | '/rooms/room-types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/buscar-sala'
    | '/dashboard'
    | '/grade'
    | '/rooms'
    | '/settings'
    | '/solicitacoes'
    | '/users'
    | '/rooms/buildings'
    | '/rooms/resources'
    | '/rooms/room-types'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/rooms'
    | '/login/'
    | '/_authenticated/buscar-sala/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/grade/'
    | '/_authenticated/rooms/'
    | '/_authenticated/settings/'
    | '/_authenticated/solicitacoes/'
    | '/_authenticated/users/'
    | '/_authenticated/rooms/buildings/'
    | '/_authenticated/rooms/resources/'
    | '/_authenticated/rooms/room-types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/': {
      id: '/_authenticated/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRouteRoute
    }
    '/_authenticated/grade/': {
      id: '/_authenticated/grade/'
      path: '/grade'
      fullPath: '/grade/'
      preLoaderRoute: typeof AuthenticatedGradeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buscar-sala/': {
      id: '/_authenticated/buscar-sala/'
      path: '/buscar-sala'
      fullPath: '/buscar-sala/'
      preLoaderRoute: typeof AuthenticatedBuscarSalaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/room-types/': {
      id: '/_authenticated/rooms/room-types/'
      path: '/room-types'
      fullPath: '/rooms/room-types/'
      preLoaderRoute: typeof AuthenticatedRoomsRoomTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRouteRoute
    }
    '/_authenticated/rooms/resources/': {
      id: '/_authenticated/rooms/resources/'
      path: '/resources'
      fullPath: '/rooms/resources/'
      preLoaderRoute: typeof AuthenticatedRoomsResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRouteRoute
    }
    '/_authenticated/rooms/buildings/': {
      id: '/_authenticated/rooms/buildings/'
      path: '/buildings'
      fullPath: '/rooms/buildings/'
      preLoaderRoute: typeof AuthenticatedRoomsBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRouteRoute
    }
  }
}

interface AuthenticatedRoomsRouteRouteChildren {
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedRoomsBuildingsIndexRoute: typeof AuthenticatedRoomsBuildingsIndexRoute
  AuthenticatedRoomsResourcesIndexRoute: typeof AuthenticatedRoomsResourcesIndexRoute
  AuthenticatedRoomsRoomTypesIndexRoute: typeof AuthenticatedRoomsRoomTypesIndexRoute
}

const AuthenticatedRoomsRouteRouteChildren: AuthenticatedRoomsRouteRouteChildren =
  {
    AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
    AuthenticatedRoomsBuildingsIndexRoute:
      AuthenticatedRoomsBuildingsIndexRoute,
    AuthenticatedRoomsResourcesIndexRoute:
      AuthenticatedRoomsResourcesIndexRoute,
    AuthenticatedRoomsRoomTypesIndexRoute:
      AuthenticatedRoomsRoomTypesIndexRoute,
  }

const AuthenticatedRoomsRouteRouteWithChildren =
  AuthenticatedRoomsRouteRoute._addFileChildren(
    AuthenticatedRoomsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRoomsRouteRoute: typeof AuthenticatedRoomsRouteRouteWithChildren
  AuthenticatedBuscarSalaIndexRoute: typeof AuthenticatedBuscarSalaIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedGradeIndexRoute: typeof AuthenticatedGradeIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSolicitacoesIndexRoute: typeof AuthenticatedSolicitacoesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRoomsRouteRoute: AuthenticatedRoomsRouteRouteWithChildren,
  AuthenticatedBuscarSalaIndexRoute: AuthenticatedBuscarSalaIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedGradeIndexRoute: AuthenticatedGradeIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSolicitacoesIndexRoute: AuthenticatedSolicitacoesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
